### ISSUE TITLE
Indítások 2

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#37]
Timed módban ne induljon addig a számláló, amíg rá nem bökök a képernyőre.

**Comment by Sasszem** [comment]
First, this should not be exclusive to timed mode.

This should not be hard. You only need to modify `Game.lua`
- in `Game:new()`, set a new flag `o.started` (later it will be `self.started`) to false
- in `Game:new()`, mofigy time updater task to only update time if that flag is set
- in `Game:touchEnd()`, set the flag

This way it will star the timer when you do you first move. It possibly won't be exact (it will start on the next whole second since game creation), and undo also won't pause it again.
